run manage-server.js 7th zb-institute lexo-corp snap-fitness
run manage-server.js 10th infocomm
run manage-server.js 0th solaris zeus-med zb-institute

816 nova-med
817 univ-energy
822 global-pharm
838 deltaone
852 galactic-cyber
854 aerocorp
859 icarus

803 titan-labs
820 applied-energetics
840 helios
868 vitalife


875 microdyne
888 taiyang-digital
888 omnia

909 omnitek +
919 infocomm +
925 The-Cave --no money
952 b-and-a
956 4sigma
995 defcomm

1002 powerhouse-fitness
1058 stormtech